1) NumPy Arrays 

In [3]:
import numpy as np

In [7]:
list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

2) NumPy Array Indexing

In [34]:
arr=np.arange(0,7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
arr_slice = arr[0:3]
arr_slice 

array([0, 1, 2])

In [37]:
arr_slice[:]=99
arr_slice 

array([99, 99, 99])

In [38]:
arr

array([99, 99, 99,  3,  4,  5,  6])